slurm: False
cores: 8
config:
  - unified_path="/nfs/turbo/lsa-jonth/jonth/unified/"
  - basedir="/home/jonth/eb_dl/paper_repo"
  - workdir="/scratch/jonth_root/jonth0/jonth/eastbay_paper/pipeline"
  - bcftools_path="/home/jonth/.local/bin/bcftools"
  - scrm_path="/home/jonth/eb_dl/paper_repo/lib/scrm/scrm"
  - psmc_path="/home/jonth/eb_dl/paper_repo/lib/psmc/psmc"
  - figures_path="/nfs/turbo/lsa-jonth/jonth/pipeline/figures"
