executor: lsf
default-resources:
  - lsf_queue="9_normal"
  - lsf_project="bmws_test"
  - nCPUs=4
  - memory=4000
  - name="JOBNAME.{rule}.{wildcards}"
  - output="logs/{rule}.{wildcards}.out"
  - error="logs/{rule}.{wildcards}.err
max-jobs-per-second: 10
max-status-checks-per-second: 1
jobs: 400
keep-going: True
rerun-incomplete: True
printshellcmds: True
directory: "/project/mathilab/colbranl/eas_selection/results/bmws"
config:
  - gpu_queue="9_lpcgpu"
