executor: slurm
default-resources:
  - mem_mb=4000
  - slurm_account=jonth1
  - slurm_partition=standard
  - runtime=60
local-cores: 4
max-jobs-per-second: 10
max-status-checks-per-second: 1
jobs: 400
keep-going: True
rerun-incomplete: True
printshellcmds: True
config:
  - figure_path="/home/jonth/turbo/bmws_admix/figures"
